//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelsBase {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HotelsBase.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add your offer.
        /// </summary>
        public static string Add_your_offer {
            get {
                return ResourceManager.GetString("Add your offer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new review.
        /// </summary>
        public static string AddNewReview {
            get {
                return ResourceManager.GetString("AddNewReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AnimationText.
        /// </summary>
        public static string AnimationText {
            get {
                return ResourceManager.GetString("AnimationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In bathroom:.
        /// </summary>
        public static string Bathroom {
            get {
                return ResourceManager.GetString("Bathroom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cencel animation.
        /// </summary>
        public static string CencelAnimation {
            get {
                return ResourceManager.GetString("CencelAnimation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coast.
        /// </summary>
        public static string Coast {
            get {
                return ResourceManager.GetString("Coast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coast:.
        /// </summary>
        public static string Coast1 {
            get {
                return ResourceManager.GetString("Coast1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        public static string Contacts {
            get {
                return ResourceManager.GetString("Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facilities and amenities.
        /// </summary>
        public static string Facilities {
            get {
                return ResourceManager.GetString("Facilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotel.
        /// </summary>
        public static string Hotel {
            get {
                return ResourceManager.GetString("Hotel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotel sort.
        /// </summary>
        public static string HotelSort {
            get {
                return ResourceManager.GetString("HotelSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotel catalog.
        /// </summary>
        public static string HotelСatalog {
            get {
                return ResourceManager.GetString("HotelСatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of berths:.
        /// </summary>
        public static string NumberBed {
            get {
                return ResourceManager.GetString("NumberBed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of rooms.
        /// </summary>
        public static string NumberofRooms {
            get {
                return ResourceManager.GetString("NumberofRooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popular first.
        /// </summary>
        public static string Popular {
            get {
                return ResourceManager.GetString("Popular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rental.
        /// </summary>
        public static string Rental {
            get {
                return ResourceManager.GetString("Rental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review.
        /// </summary>
        public static string Review {
            get {
                return ResourceManager.GetString("Review", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rooms.
        /// </summary>
        public static string Rooms {
            get {
                return ResourceManager.GetString("Rooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room size:.
        /// </summary>
        public static string RoomSize {
            get {
                return ResourceManager.GetString("RoomSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rub. per month.
        /// </summary>
        public static string Rub {
            get {
                return ResourceManager.GetString("Rub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter search term.
        /// </summary>
        public static string Seach {
            get {
                return ResourceManager.GetString("Seach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        public static string Services {
            get {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smoking:.
        /// </summary>
        public static string Smoking {
            get {
                return ResourceManager.GetString("Smoking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by number of rooms.
        /// </summary>
        public static string SortRoom {
            get {
                return ResourceManager.GetString("SortRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by Stars.
        /// </summary>
        public static string SortStars {
            get {
                return ResourceManager.GetString("SortStars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speak.
        /// </summary>
        public static string Speak {
            get {
                return ResourceManager.GetString("Speak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start animation.
        /// </summary>
        public static string StastAnimation {
            get {
                return ResourceManager.GetString("StastAnimation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of rent:.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpopular first.
        /// </summary>
        public static string Unpopular {
            get {
                return ResourceManager.GetString("Unpopular", resourceCulture);
            }
        }
    }
}
